# Generated by Django 4.2.7 on 2025-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='audit_period_end',
            field=models.DateField(blank=True, help_text='End date of audit period', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='audit_period_start',
            field=models.DateField(blank=True, help_text='Start date of audit period', null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='require_palms_sheets',
            field=models.BooleanField(default=False, help_text='Whether PALMS data sheets are required for this report'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='uploaded_file_names',
            field=models.JSONField(blank=True, default=list, help_text='List of all uploaded files with metadata'),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='week_of_date',
            field=models.DateField(blank=True, help_text='The week this audit represents (e.g., 2025-01-28)', null=True),
        ),
    ]
