# Generated by Django 4.2.7 on 2025-10-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_password', models.CharField(default='admin123', max_length=100)),
                ('failed_admin_attempts', models.IntegerField(default=0)),
                ('admin_lockout_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='password',
            field=models.CharField(default='chapter123', max_length=100),
        ),
    ]
