# Generated by Django 4.2.7 on 2025-10-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_adminsettings_chapter_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='admin_password',
            field=models.CharField(default='admin123', max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='password',
            field=models.CharField(default='chapter123', max_length=255),
        ),
    ]
