# Generated by Django 4.2.17 on 2025-10-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_increase_password_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='admin_password',
            field=models.CharField(help_text='Bcrypt hashed admin password. Set via management command or admin panel.', max_length=255),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
