# Generated by Django 4.2.7 on 2025-10-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_referral_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetoone',
            name='meeting_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='onetoone',
            name='week_of',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='date_given',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='week_of',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyfcb',
            name='date_closed',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tyfcb',
            name='week_of',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyfcb',
            name='within_chapter',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
