# Generated by Django 4.2.25 on 2025-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onetoone',
            index=models.Index(fields=['member1', 'meeting_date'], name='oto_member1_date_idx'),
        ),
        migrations.AddIndex(
            model_name='onetoone',
            index=models.Index(fields=['member2', 'meeting_date'], name='oto_member2_date_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['giver', 'date_given'], name='referral_giver_date_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['receiver', 'date_given'], name='referral_receiver_date_idx'),
        ),
        migrations.AddIndex(
            model_name='tyfcb',
            index=models.Index(fields=['receiver', 'within_chapter'], name='tyfcb_receiver_chapter_idx'),
        ),
        migrations.AddIndex(
            model_name='tyfcb',
            index=models.Index(fields=['receiver', 'date_closed'], name='tyfcb_receiver_date_idx'),
        ),
    ]
