# Generated by Django 4.2.25 on 2025-10-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='member',
            name='member_first_name_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='member',
            name='member_last_name_not_empty',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='member_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='member_created_idx',
        ),
        migrations.RenameIndex(
            model_name='member',
            new_name='member_chapter_active_idx2',
            old_name='member_chapter_active_idx',
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['classification'], name='member_classification_idx'),
        ),
    ]
