name: Frontend CI

on:
  push:
    branches: [main, develop, staging, production]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [main, develop, staging, production]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type checking
        run: npx tsc --noEmit

      - name: Lint with ESLint
        run: npm run lint --if-present || echo "No lint script found, skipping..."
        continue-on-error: true

      - name: Run tests with coverage
        run: npm run test:ci
        env:
          CI: true

      - name: Check coverage thresholds
        run: |
          echo "Checking coverage thresholds (80% minimum)..."
          npm run test:coverage -- --passWithNoTests
        env:
          CI: true

      - name: Build production bundle
        run: npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./frontend/coverage/coverage-final.json
          flags: frontend
          name: frontend-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
          retention-days: 7
